title: Nishiki Liu
email: hello@nshki.com
description: "Personal blog of a software engineer."
baseurl: ""
url: "https://nshki.com"
permalink: /:title/
twitter:
  username: nshki_
  card: summary
github:
  username: nshki
plugins:
  - jekyll-feed
